import {
  Shuffle,
  Palette,
  ScanSearch,
  Copy,
  EyeOff,
  Calculator,
  Puzzle,
  Type,
  Shapes,
  ArrowLeftRight,
  Car,
  Target,
  Slice,
  Scaling,
  TowerControl,
  Brain,
  Eye,
  Gamepad2,
  MemoryStick,
  Box,
  FlipHorizontal,
} from "lucide-react";

export const GAME_CATEGORIES = [
  {
    key: "memory",
    name: "Memoria",
    icon: MemoryStick,
    color: "yellow",
    games: [
      { key: "memory-random", name: "Juego aleatorio", icon: Shuffle },
      { key: "memory-color-sequence", name: "Secuencia de Colores", icon: Palette },
      { key: "memory-find-new", name: "Encuentra el Nuevo", icon: ScanSearch },
      { key: "memory-pair-cards", name: "Par de Cartas", icon: Copy },
    ],
  },
  {
    key: "reasoning",
    name: "Razonamiento",
    icon: Brain,
    color: "blue",
    games: [
      { key: "reasoning-random", name: "Juego aleatorio", icon: Shuffle },
      { key: "reasoning-hidden-colors", name: "Colores Ocultos", icon: EyeOff },
      { key: "reasoning-sum-numbers", name: "Suma Números", icon: Calculator },
      { key: "reasoning-reorder-blocks", name: "Reordenar Bloques", icon: Puzzle },
    ],
  },
  {
    key: "attention",
    name: "Atención",
    icon: Eye,
    color: "orange",
    games: [
      { key: "attention-random", name: "Juego aleatorio", icon: Shuffle },
      { key: "attention-color-words", name: "Palabras de Colores", icon: Type },
      { key: "attention-unique-figure", name: "Figura Única", icon: Shapes },
      { key: "attention-left-right", name: "Izquierda o Derecha", icon: ArrowLeftRight },
    ],
  },
  {
    key: "coordination",
    name: "Coordinación",
    icon: Gamepad2,
    color: "green",
    games: [
      { key: "coordination-random", name: "Juego aleatorio", icon: Shuffle },
      { key: "coordination-road-cars", name: "Coches en la Carretera", icon: Car },
      { key: "coordination-jumping-circle", name: "Círculo saltarín", icon: Target },
      { key: "coordination-cut-fruits", name: "Cortar Frutas", icon: Slice },
    ],
  },
  {
    key: "visuospatial",
    name: "Visuoespacial",
    icon: Box,
    color: "pink",
    games: [
      { key: "visuospatial-random", name: "Juego aleatorio", icon: Shuffle },
      { key: "visuospatial-scale", name: "Escala", icon: Scaling },
      { key: "visuospatial-symmetry", name: "Simetría", icon: FlipHorizontal },
      { key: "visuospatial-block-tower", name: "Torre de Bloques", icon: TowerControl },
    ],
  },
];
