// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdudrydyvrbhvyigpztm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkdWRyeWR5dnJiaHZ5aWdwenRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzQ0NjMsImV4cCI6MjA2NTUxMDQ2M30.TcwiepA2GMesx40zonMOv0C9jWfESWU58eOwKH8Lb8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);